# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test || travis_terminate 1;

before_install:
  - openssl aes-256-cbc -K $encrypted_86f8900ca297_key -iv $encrypted_86f8900ca297_iv
    -in lab-devops-cloud-amartins-3af04f3a6531.json.enc -out ../lab-devops-cloud-amartins-3af04f3a6531.json
    -d

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-alexmart001
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://devopslab-alexmart001.herokuapp.com/ | grep Hello || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-amartins-3af04f3a6531.json
        project: lab-devops-cloud-amartins
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devops-cloud-amartins.uc.r.appspot.com/ | grep Hello || travis_terminate 1;

